-- Use the database
USE alx_book_store;

-- ======================
-- TABLE: AUTHORS
-- ======================
CREATE TABLE IF NOT EXISTS AUTHORS (
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(215) NOT NULL
);

-- ======================
-- TABLE: CUSTOMERS
-- ======================
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL,
    ADDRESS TEXT
);

-- ======================
-- TABLE: BOOKS
-- ======================
CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT,
    PRICE DOUBLE,
    PUBLICATION_DATE DATE,
    CONSTRAINT FK_BOOKS_AUTHORS FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHORS(AUTHOR_ID)
);

-- ======================
-- TABLE: ORDERS
-- ======================
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- ======================
-- TABLE: ORDER_DETAILS
-- ======================
CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDERDETAILID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY DOUBLE,
    CONSTRAINT FK_ORDERDETAILS_ORDERS FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_ORDERDETAILS_BOOKS FOREIGN KEY (BOOK_ID)
        REFERENCES BOOKS(BOOK_ID)
);
